services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx-container
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend-1
      - backend-2
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-container
  backend-1:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-container-1
  backend-2:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-container-2
